package com.hallak.SentinelAI.dtos;

public enum ScanType {
    XSS,
    LFI,
    SQL_INJECTION,
    OPEN_REDIRECT,
    INSECURE_HEADERS,
    SSRF,
    CORS_MISCONFIGURATION,
    COMMAND_INJECTION,
    WEAK_AUTHENTICATION,
    SENSITIVE_DATA_EXPOSURE,
    CSRF,
    RATE_LIMIT_BYPASS,
    IDOR,
    JWT_MISCONFIGURATION;
}
